### ISSUE TITLE
Silent time

### ISSUE THREAD

**Issue by juliacs** [lucaju/onchance#11]
pode ser viagem, mas eu acho que seria bom ter um mecanismo para, quando um video começar, ignorar por alguns segundos (ou uma certa % do video) os inputs do user. depois que passar o tempo, o ultimo input é usado para dar continuidade na conversa. talvez teriamos que ter algumas exceções ao silêncio (do tipo "stop").

**Comment by lucaju** [comment]
Tem que pensar mais sobre isso. Ate mesmo como implementar.

1. Desabilitar o input do usuario - vc vai tirar o principal agenciamento. 
2. Deixar ele escrever, mas não envia... pior ainda... o usuario vai achar que ta com bug.
3. Receber o input mas não enviar pro dialogflow.
4. receber os inputs mas so mandar para o dialog flow no final (mandar todos os inputs).
5. Manda tudo pro dialogflow, mas segura as resposta por um tempo.

Usar o ultimo input pode ser incoerente. Digamos que tente escrever, mas nada acontece... ai escrevo de novo e de novo..
Exemplo:
"Massa esse video" (nada de resposta)
"gostei do video" (nada)
"alooooo" - ultimo input.. manda pro dialog flow... ele entende como welcome e responde "hi, my name is jana..."
hahhaahah

**Comment by juliacs** [comment]
você tem razao. talvez isso possa ser resolvido com aquela funçao do callback scriptado com frases do tipo : "wait a sec, let's finish the video first." coisas assim.  que você acha?

**Comment by juliacs** [comment]
e talvez a gente tenha que ao mesmo tempo ignorar o input do usuario para nao avançar a conversa. faz sentido?

**Comment by juliacs** [comment]
algo como : durante a primeira metade do video, o inout do usuario é ignorado e o bot responde "wait a sec, let's watch the video". depois libera o input e se o usario tiver falado alguma coisa, o ultimo input é usado pra continuar a conversa.
