### ISSUE TITLE
video delay

### ISSUE THREAD

**Issue by juliacs** [lucaju/onchance#12]
ter um mecanismo para criar um delay para o play do video (de acordo com o tamanho do texto do intent)

**Comment by juliacs** [comment]
neste mecanismo, as múltiplas respostas de cada intent (texto ou payload) aparecem em sequencia (e não ao mesmo tempo, como esta agora). no caso da resposta em video (payload), a sequencia das respostas viria depois do final do video.

**Comment by lucaju** [comment]
Duplicate of # #6
