### ISSUE TITLE
Resposta-texto do bot depois de video

### ISSUE THREAD

**Issue by juliacs** [lucaju/onchance#6]
Caso o usuario nao escreva nada durante toda a duraçao do video, quando o video chegar ao final o bot envia uma pergunta do tipo "gostou do video?"

**Comment by lucaju** [comment]
Isso seria uma resposta "scriptada" (nossa), ou seria uma provocação ao DialogFlow para o bot fazer essa pergunta?

**Comment by juliacs** [comment]
se tem como ser os dois, acho que é o ideal :) a resposta hard scriptada e uma provocaçao ao bot. mas acho que preciso entender melhor como funciona essa provocaçao, você me explica melhor depois?

**Comment by lucaju** [comment]
Nao pode ser os dois. Se não o bot vai falar duas coisas: vinda da interface, e vinda do dialogflow.
A gente teve outra ideia esses dias para resolver a fala pos video... o callback, lembra?

Sequencia logica:
- Quando o video terminar, o bot deve falar. Pergunta: qualquer video? ou apenas alguns? se for alguns, como saber qual? Teria que mandar junto no payload.
- Decidido que esse video especifico precisa de um callback (o bot fala alguma coisa), o que ele vai falar? Pode ser uma resposta especifica ("voce gostou?) defina diretamente no código (isso é, sempre a mesma pergunta).
Ou pode vir junto do callback via payload. exemplo de um payload com callback:
```
{
action: play,
media: video,
subject: sports,
callback: {
  event: afterVideo,
  message: "você gostou?"
  }
}
```

Lembrou que depois de decidirmos, tenho que implementar isso no codigo.
Isso da bastante flexibilidade para as resposta do bot. Mas tambem mais trabalho para fazer funcionar. :)

Deu pra entender? Posso tentar explicar melhor se qusier.

**Comment by juliacs** [comment]
nao tinha visto esse seu comentario, foi mal! pode ser uma soluçao. outra soluçao talvez esteja nos comentarios do issue sobre delay do video. vamos conversar sobre isso depois. valeu!

**Comment by lucaju** [comment]
Implementei usando a propria ordem de messagens no Dialogflow. Na pos-processamento adicionamos delays para cada mensagem. No caso do video, usamos a duração adicionada como metadado na coleção de videos. Melhor seria usar a duração do video vindo do metadado do arquivo, dai fica mais preciso.
Vamos testar.

524bf2cf1f6aca9b5becd278e48fceb6b0044e9f
