### ISSUE TITLE
Balao de info sobre o video 

### ISSUE THREAD

**Issue by juliacs** [lucaju/onchance#8]
disponivel para o usuario?

**Comment by lucaju** [comment]
Tipo um botão na interface. Dai o usuario clica e aparece uma janela com descrição... ou ainda, o bot fala a descrição... o que acha?

**Comment by juliacs** [comment]
é isso! acho que a descriçao na janela do video, tenho medo de interfirir muito no andamento da conversa se for o bot falando.

**Comment by lucaju** [comment]
E eu queria evitar qualquer botão... por mim teria que ser tudo pelo bot... uma limitação interessante.
Mas ... botão ta valendo. O botão em si pode ficar na parte do video, no canto inferior direito por exemplo.
Mas onde mostrar a informação?

Veja um mock up.
A- uma janela por cima do video.
B- A gente coloca na boca do bot
C - fica na parte da conversa, mas não é o bot que fala. Fica tipo um narrador :)
o que vc acha?

<img width="923" alt="Screen Shot 2020-07-17 at 2 30 31 PM" src="https://user-images.githubusercontent.com/1254739/87819602-7ed88980-c83a-11ea-810f-b408e7e151a5.png">

**Comment by juliacs** [comment]
muito bom!!!

**Comment by juliacs** [comment]
Eu fiquei pensando nessa historia de um "narrador", achei muito bom! ele podia colocar a info sobre cada video e dar aquele texto de intro (você ja tinha sugerido isso, se nao me engano)... que você acja
o texto é assim : 
"Congratulations on your new job! You were just hired as a journalist and your first assignment is to collaborate with your colleague Jana on a story about predictive algorithms. Help Jana writing this story with the research material she’ll show you."

**Comment by lucaju** [comment]
8b2894d5de4547450420ec156f058078e6c40069
